import iJobs from 'src/interfaces/interfaces';

export const jobs: Array<iJobs> = [
  {
    id: 1,
    title: 'Frontend Developer',
    company: 'TechVision',
    description: 'Разработка и поддержка веб-приложений',
    salaryFrom: 1800,
    salaryTo: 2800,
    currency: 'EUR',
    location: 'Riga',
    remote: true,
    employmentType: 'full-time',
    experience: '2-4 years',
    skills: ['JavaScript', 'TypeScript', 'React'],
    createdAt: '2026-08-01',
    isActive: true,
  },
  {
    id: 2,
    title: 'Backend Developer',
    company: 'CloudSoft',
    description: 'Разработка серверных приложений и REST API',
    salaryFrom: 2200,
    salaryTo: 3500,
    currency: 'EUR',
    location: 'Vilnius',
    remote: true,
    employmentType: 'full-time',
    experience: '3-5 years',
    skills: ['Node.js', 'NestJS', 'PostgreSQL'],
    createdAt: '2026-08-03',
    isActive: true,
  },
  {
    id: 3,
    title: 'QA Engineer',
    company: 'DigitalWorks',
    description: 'Тестирование веб- и мобильных приложений',
    salaryFrom: 1400,
    salaryTo: 2200,
    currency: 'EUR',
    location: 'Tallinn',
    remote: false,
    employmentType: 'full-time',
    experience: '1-3 years',
    skills: ['Jest', 'Postman', 'Cypress'],
    createdAt: '2026-08-05',
    isActive: true,
  },
  {
    id: 4,
    title: 'React Native Developer',
    company: 'MobileLab',
    description: 'Разработка и поддержка мобильных приложений',
    salaryFrom: 2000,
    salaryTo: 3200,
    currency: 'EUR',
    location: 'Riga',
    remote: true,
    employmentType: 'full-time',
    experience: '2-5 years',
    skills: ['React Native', 'React', 'TypeScript'],
    createdAt: '2026-08-07',
    isActive: true,
  },
  {
    id: 5,
    title: 'DevOps Engineer',
    company: 'Infrastructure Pro',
    description: 'Настройка серверов, инфраструктуры и CI/CD',
    salaryFrom: 2500,
    salaryTo: 4000,
    currency: 'EUR',
    location: 'Warsaw',
    remote: true,
    employmentType: 'full-time',
    experience: '4-6 years',
    skills: ['Docker', 'Kubernetes', 'AWS'],
    createdAt: '2026-08-10',
    isActive: false,
  },
];
